# Generated by Django 2.0.4 on 2018-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20180406_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ask_date',
            field=models.DateTimeField(null=True),
        ),
    ]
