# Generated by Django 2.0.4 on 2018-04-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20180407_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
